# Generated by Django 4.1.4 on 2023-02-03 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=50)),
                ('comp_name', models.CharField(default='', max_length=50)),
                ('series', models.CharField(default='', max_length=50)),
                ('desc', models.CharField(max_length=300)),
                ('price', models.IntegerField(default=0)),
                ('pub_date', models.DateField()),
                ('image', models.ImageField(default='', upload_to='shop/images')),
            ],
        ),
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co_name1', models.CharField(default='', max_length=100)),
                ('stars', models.IntegerField()),
                ('co_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vivo.product')),
            ],
        ),
    ]
